CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY, 
  name VARCHAR (155) NOT NULL, 
  username VARCHAR (50) UNIQUE NOT NULL, 
  password VARCHAR (255) NOT NULL, 
  email VARCHAR (255) UNIQUE NOT NULL, 
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);